name: flutter_template
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # 路由
  go_router: ^13.0.1

  # 存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 状态管理

  # app升级库
  upgrader: ^8.4.0

  # 数据类 / 联合体 / 模式匹配 / 克隆的代码生成器
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # 网络
  dio: ^5.4.0

  # 日志
  logger: ^2.0.2+1

  # 状态管理
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4
  riverpod_annotation: ^2.3.3

  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter 规范
  flutter_lints: ^2.0.0
  # 代码生成工具
  build_runner: ^2.4.7
  # freezed 工具
  freezed: ^2.4.6
  json_serializable: ^6.7.1

  # riverpod工具
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7


flutter:
  uses-material-design: true